version: '3.5'

services:
  postgres:
    container_name: DATABASE
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin

    ports:
      - "${PGADMIN_PORT:-5050}:80"

    networks:
      - postgres

  api:
    build: .
    ports:
      - "8000:8000"
    networks:
      - postgres
    depends_on:
      - postgres
    volumes:
      - minhaaplicao:/usr/src/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    # env_file:
    #   - ./.env
    environment:
      - DATABASE_HOSTNAME=DATABASE #nome do container do postgres
      - DATABASE_PORT=5432
      - DATABASE_NAME=FastAPI
      - DATABASE_USER=postgres
      - DATABASE_PASSWOR=postgres
      - DATABASE_DRIVER=postgresql
      - SECRET_KEY=c82d1b07d7f2b4f5bb18e4ede23b1347f863e748
      - ALGORITHM=HS256
      - ACESS_TOKEN_EXPIRE_DAYS=1
networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin:
  minhaaplicao:
